InetecTracker/InetecTracker/Controllers/ControlController.cs
using InetecTracker.Infrastructure.Interfaces;
using InetecTracker.Infrastructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InetecTracker.Controllers
{
    [Authorize]
    public class ControlController : Controller
    {


        private readonly ITicketCommentService commentService = null;
        private readonly IAccountService accountService = null;


        public ControlController(ITicketCommentService CommentService, IAccountService AccountService)
        {
            commentService = CommentService;
            accountService = AccountService;
        }

        private int currentUserId()
        {
            var currentUser = HttpContext.User.Identity.Name;
            return accountService.GetAccountId(currentUser);
        }

        public ActionResult TicketCommentControl(int ticketId)
        {
            int currentId = currentUserId();
            ViewBag.isAvaliable = commentService.IsCommentAvailable(ticketId, currentId);
            return PartialView("TicketCommentControl", ticketId);
        }

        public ActionResult TicketCommentList(int ticketid)
        {
            List<TicketCommentModel> model = commentService.GetTicketComments(ticketid);
            return PartialView("TicketCommentList", model);
        }

        public ActionResult TicketCommentForm(int ticketId)
        {
            TicketCommentModel model = new TicketCommentModel { TicketId = ticketId };
            return PartialView("TicketCommentForm", model);
        }

        [HttpPost]
        public ActionResult AddComment(int ticketId, string comment)
        {
            if (!String.IsNullOrWhiteSpace(comment))
            {
                TicketCommentModel model = new TicketCommentModel();
                model.Comment = comment;
                model.TicketId = ticketId;
                model.CreateBy = new IdName { Id = currentUserId(), Name = String.Empty };

                commentService.AddTicketComment(model);
            }
            return TicketCommentList(ticketId);
        }
    }
}

InetecTracker/InetecTracker/Views/Control/TicketCommentControl.cshtml
@model int
@{
    bool isAvaliable = ViewBag.isAvaliable ?? false;
}

<hr />

<div class="jumbotron">
    <div id="comment-ctrl-@Model">
        @Html.Action("TicketCommentList", "Control", new { area = String.Empty, ticketid = Model })
    </div>

    @if (isAvaliable)
    {
        @Html.Action("TicketCommentForm", "Control", new { area = String.Empty, ticketid = Model })
    }
    else
    {
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            Current user doesn't have permissions for comment control
        </div>
    }
</div>

InetecTracker/InetecTracker/Views/Control/TicketCommentForm.cshtml
@using InetecTracker.Infrastructure.Models
@model TicketCommentModel



<form class="form-horizontal">
    @Html.HiddenFor(x=>x.TicketId)
    <div class="form-group">
        @Html.LabelFor(x => x.Comment, "Comment", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Comment, new { @class = "form-control", placeholder = "Comment" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <a href="javascript:addComment()" class="btn btn-default">Add comment</a>
        </div>
    </div>
</form>


<script type="text/javascript">
    addComment = function () {

        var ticketId = $('#TicketId').val();
        var comment = $('#Comment').val();

        if (ticketId && comment.length > 0) {
            var postData = {
                ticketId: ticketId,
                comment: comment
            }

            $.ajax({
                url: '@Url.Action("AddComment", "Control", new { area = String.Empty})',
                type: 'POST',
                data: postData,
                success: function (dataHtml) {
                    $('#Comment').val('');
                    $('#comment-ctrl-@Model.TicketId').html(dataHtml);
                }
            });

        };
    }

</script>

InetecTracker/InetecTracker/Views/Control/TicketCommentList.cshtml
@using InetecTracker.Infrastructure.Models
@model List<TicketCommentModel>
<div class="comments-cnt ">
    @foreach (var item in Model.OrderBy(x => x.Id))
    {
        <div class="comment-item">
            <div class="comment">@item.Comment</div>
            <div class="comment-details">@item.CreateBy.Name - @item.CreateDate.ToString()</div>
        </div>
    }
</div>